### PR TITLE
Fix test and npm issues

### PR DESCRIPTION
**Pull request by FelixFurtmayr**

### CODE REVIEW

**Comment by FelixFurtmayr** [comment]
@msurdi test was fixed, the issue of ve3 solved and his changes from the pull request he closed were added to the readme. please review and merge. thank you.

**Comment by FelixFurtmayr** [comment]
oh - and a npm publish would be nice after the merge, so we can use the improved version. Thank you :-)

**Review by msurdi — APPROVED** [review]

**Comment by msurdi** [comment]
Just published `frontend-dependencies@1.1.7`

@FelixFurtmayr Do you have an username at npmjs.com? If so, I'd like to give yo permissions to publish, just in case I'm not available and to avoid a single point of failure :-).

**Comment by FelixFurtmayr** [comment]
I'm not sure if I already have the right to publish on npm? Anyway - my name on npm is felix_furtmayr. Do I have the right on github to approve merge requests? Would be also nice. 
Although we would stick to the schema we did (I might write something, you do a review), if it does not bother you.

**Comment by msurdi** [comment]
@FelixFurtmayr sorry for my late answer, I've just confirmed you do have permissions to publish on NPM and to merge PRs as well. I'm happy to follow the current workflow too. Just wanted to confirm you're not blocked if for some reason I'm not available. Thanks for your great work!.

**Pull request merged**
