### PR TITLE
added felix as contributor

### PR DESCRIPTION
**Pull request by FelixFurtmayr**
Thanks for mentioning me.
As everything was working, I forgot about this.

### CODE REVIEW

**Comment by FelixFurtmayr** [comment]
Hi msurdi,

as I tested our package the first time live in a app of mine, I experienced long, long, long waiting times due to several npm installs in row.
I would be happy if you could review and publish the module. Thank you!

Regards Felix

### Summary of my changes
* I decided to do everything with a single command which is much faster.
* Also I added a colored logging for better understanding of the console output.

### My experience so far
I'm really happy with the module. Now I can get rid of some shitty code in my Gruntfiles.
First time I tried to use it - nothing worked; npm error messages. After deleting the node_modules complete, everything was fine.

**Review by msurdi — APPROVED** [review]
Awesome!

**Comment by msurdi** [comment]
And published to npm as 1.1.0 too

**Comment by FelixFurtmayr** [comment]
Thank you very much!

**Pull request merged**
