### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by chauhan739**
Added MIT License. MIT license in mentioned in the [npmjs.com](https://www.npmjs.com/package/frontend-dependencies) but no LICENSE file is found in the repo.

### CODE REVIEW

**Comment by chauhan739** [comment]
@msurdi  I am currently unable to add you as a reviewer. I kindly request you to review my proposed changes, as I aim to add the MIT License to this repository. I am using this package in a project that mandates the use of licensed packages with a LICENSE file included in their repository. Your review and approval would be greatly appreciated.

Thank you.

**Review by FelixFurtmayr — APPROVED** [review]

**Comment by msurdi** [comment]
Sorry, I’m late here. This looks good to me.

**Comment by FelixFurtmayr** [comment]
the checks all passed, but I had to run it twice.

@chauhan739  I hope the code helps you.

**Comment by chauhan739** [comment]
Hi @FelixFurtmayr,
I wanted to follow up on this PR and inquire about the timeline for updating the file on npmjs.com. This is crucial as I need to upgrade the version in my project's `package.json`.

**Comment by FelixFurtmayr** [comment]
@chauhan739 can you help with that? From my point of view those points can be updated:
- package.json update - there are just two dependencies
- update test cases: add new node versions in .github/workflows/node.js.yml like maybe version 20 and something above?
- remove the note in the readme: "NOTE: There is a breaking change from Version 0.4.0 to 1.0.0.  ..."
- test if everything still works

have I forgotten something?

**Comment by chauhan739** [comment]
@FelixFurtmayr please clarify one thing. Do you want me to update the mentioned items in your repository, or should I make these updates in the `node_modules` file for my project?

**Comment by msurdi** [comment]
I can do this, but I'm not sure if I'll have time to do it before the weekend.

**Comment by msurdi** [comment]
@chauhan739 I've published 2.0.1 to NPM with just the license change to unblock you 👍

**Comment by chauhan739** [comment]
Thanks @msurdi and @FelixFurtmayr a lot ❤️❤️

**Pull request merged**
