### PR TITLE
update travis to latest versions

### PR DESCRIPTION
**Pull request by FelixFurtmayr**

### CODE REVIEW

**Comment by FelixFurtmayr** [comment]
@msurdi I forgot you built in travis here already. I updated the versions and now builds again. 

I forgot it for one reason: there were no tests show in the other pull request - I don't know why. Here the new github actions are also shown as tests.

Should we remove travis - and maybe create another badge in the readme for the build status?
Next time we will have forgotten again ...
I think it is not required to have two testing environments and I don't know how to show travis here again in github.

**Comment by msurdi** [comment]
Hi @FelixFurtmayr , totally agree. I think we can get rid of travis, as nowadays I think we're better using Github actions.

**Review by msurdi — DISMISSED** [review]

**Comment by FelixFurtmayr** [comment]
@msurdi  thanks for your approval - I updated the badge in the readme and removed the travis file. please confirm, so I can merge it. thank you.

**Review by msurdi — APPROVED** [review]
Awesome!

**Pull request merged**
