### PR TITLE
improve speed: don't instsall dev deps =>not needed

### PR DESCRIPTION
**Pull request by FelixFurtmayr**

### CODE REVIEW

**Review by msurdi — APPROVED** [review]

**Comment by FelixFurtmayr** [comment]
Hi msurdi, thanks for the quick review :-)

**Comment by msurdi** [comment]
I'm on vacation and can't publish it right now because I don't have my laptop. Will do it in a couple weeks and also give you permissions on npm to do it yourself

**Comment by FelixFurtmayr** [comment]
This is a good idea with the right to publish on npm for me.
No problem if it takes some time - it is just a speed improvement, I don't need it right now.
Have a nice holiday :-)

**Comment by msurdi** [comment]
Hey @FelixFurtmayr , do you have an username at npmjs.com ? I'd like to give you permission to publish new versions instead of doing it myself.

**Comment by FelixFurtmayr** [comment]
Hi msurdi, my name is "felix_furtmayr" on npm. Thank you.

**Comment by msurdi** [comment]
Ok, I've created the _frontend-dependencies_ organization, added the package _frontend-dependencies_ to it, and then sent you an invitation to be a _member_ of this organization. As far as I understand that should give you enough permissions to publish new versions but this is my first time doing this on npmjs so there could be something missing still.

Please, give it a try and let me know.

**Comment by FelixFurtmayr** [comment]
Perfect - worked on the first run.
Dealing with organizations and migrating things can be a bit difficult (or not everything might work perfect from my experience). At least the npm support is very good. Felix loves npm ;-)

**Pull request merged**
